spring:
  datasource:
    url: jdbc:mysql://172.16.3.10:3306/nacos?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: otcdb.dev.10
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8099