spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://172.16.3.10:3306/nacos?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: otcdb.dev.10
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: wall,stat
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 200
    logAbandoned: false
    removeAbandoned: false
    removeAbandonedTimeout: 1800
    initialSize: 5
    maxActive: 30
    minIdle: 5
    maxWait: 10000